services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"  # Consul UI and API
    networks:
      - my-network
    command: "consul agent -dev -client=0.0.0.0"

  web-api:
    build:
      context: ./CloudComputing
    ports:
      - "8080:80"
    environment:
      - CONSUL_URI=http://consul:8500
    networks:
      - my-network

  web-app:
    build:
      context: ./CloudComputingWeppApp
    ports:
      - "8081:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
